name: "ec2-instance-connect-deploy"
description: "Deploy to AWS EC2 instance using EC2 Instance Connect"
branding:
  icon: fast-forward
  color: orange

inputs:
  access-key-id:
    description: "AWS_ACCESS_KEY_ID"
    required: true
  secret-access-key:
    description: "AWS_SECRET_ACCESS_KEY"
    required: true
  default-region:
    description: "AWS_DEFAULT_REGION"
    required: true
  user-name:
    description: "The user name"
    required: true
  instance-id:
    description: "The EC2 instance id"
    required: true
  mssh-path:
    description: 'Path to mssh'
    required: true
    default: "/home/ubuntu/.local/bin/mssh"        
  command:
    description: "command to be executed"
    required: false
    default: "echo 'Hello world'"

outputs:
  result:
    description: "Output of the command"
    value: ${{ steps.ec2-ssh.outputs.result }}

runs:
  using: "composite"
  steps:
    - id: ec2-ssh
      shell: bash
      run: |
        AWS_ACCESS_KEY_ID=${{ inputs.access-key-id }} \
        AWS_SECRET_ACCESS_KEY=${{ inputs.secret-access-key }} \
        AWS_DEFAULT_REGION=${{ inputs.default-region }}

        echo "${{ inputs.command }}" > $HOME/shell.sh
        cat $HOME/shell.sh

        "${{ inputs.mssh-path }}" "${{ inputs.user-name }}@${{ inputs.instance-id }}" -r ${AWS_DEFAULT_REGION} bash --login <  $HOME/shell.sh | tee action_output

        cat action_output | tr  '\n' '#'  | tr  '\r' '#'  |  tr  '%' '#'  > single_lined_output
     
        content=`cat single_lined_output`
        echo "result=$(cat single_lined_output)" >> $GITHUB_OUTPUT

        rm action_output
        rm single_lined_output